<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AssimpNetter" />
    <PackageReference Include="Intellenum" />
    <PackageReference Include="ShaderSlang.Net" />
    <PackageReference Include="Silk.NET.Input" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameDotNet.Core\GameDotNet.Core.csproj" />
    <ProjectReference Include="..\GameDotNet.Input\GameDotNet.Input.csproj" />
  </ItemGroup>
</Project>