<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Arch-Events" Version="2.1.0" />
    <PackageVersion Include="Arch.Relationships" Version="1.0.1" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.2.1" />
    <PackageVersion Include="AssimpNetter" Version="6.0.2.1" />
    <PackageVersion Include="AutoFactories.Microsoft.DependencyInjection" Version="1.1.19" />
    <PackageVersion Include="Avalonia" Version="11.2.8" />
    <PackageVersion Include="Avalonia.Controls.TreeDataGrid" Version="11.1.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.8" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="11.2.8" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.2.8" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="ByteSize" Version="2.1.2" />
    <PackageVersion Include="dotVariant" Version="0.5.3" />
    <PackageVersion Include="FluentAvaloniaUI" Version="2.3.0" />
    <PackageVersion Include="Injectio" Version="5.1.0" />
    <PackageVersion Include="Intellenum" Version="1.0.6" />
    <PackageVersion Include="MessagePipe" Version="1.8.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.DotNet.ILCompiler" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.AutoActivation" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool.DependencyInjection" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.2.1" />
    <PackageVersion Include="Microsoft.Toolkit.HighPerformance" Version="7.1.2" />
    <PackageVersion Include="Nito.Disposables" Version="2.5.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.8.0-beta.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
    <PackageVersion Include="QuikGraph" Version="2.5.0" />
    <PackageVersion Include="ReactiveUI.Fody" Version="19.5.41" />
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.1" />
    <PackageVersion Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.File.GZip" Version="1.0.2" />
    <PackageVersion Include="ServiceScan.SourceGenerator" Version="2.3.4" />
    <PackageVersion Include="shaderc.net" Version="0.1.0" />
    <PackageVersion Include="ShaderSlang.Net" Version="0.1.0-306" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Silk.NET.Core" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Input" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Input.Common" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.21.0" />
    <PackageVersion Include="Silk.NET.WebGPU.Extensions.WGPU" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.WebGPU.Native.WGPU" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Windowing.Extensions" Version="2.22.0" />
    <PackageVersion Include="Silk.NET.Windowing.Sdl" Version="2.22.0" />
    <PackageVersion Include="Simple.Avalonia.Hosting" Version="8.5.0" />
    <PackageVersion Include="TruePath" Version="1.10.0" />
    <PackageVersion Include="TUnit" Version="1.5.80" />
    <PackageVersion Include="ValueTaskSupplement" Version="1.1.0" />
    <PackageVersion Include="Vogen" Version="8.0.4" />
    <PackageVersion Include="ZLinq" Version="1.5.3" />
  </ItemGroup>
</Project>