<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameDotNet.Core\GameDotNet.Core.csproj"/>
        <ProjectReference Include="..\GameDotNet.Hosting\GameDotNet.Hosting.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <RdXmlFile Include="Rd.xml"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets\MonkeyScene.dae">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Mesh.frag">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Mesh.vert">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <None Update="Assets\Monkey.dae">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>