<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameDotNet.Graphics\GameDotNet.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.WebGPU.Extensions.WGPU" />
    <PackageReference Include="Silk.NET.WebGPU.Native.WGPU" />
  </ItemGroup>
</Project>