<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ThirdParty\SpirVReflectSharp\SpirvReflectSharp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Arch-Events" />
    <PackageReference Include="ByteSize" />
    <PackageReference Include="dotVariant" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Toolkit.HighPerformance" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Silk.NET.Core" />
    <PackageReference Include="System.Reactive.Interfaces" />
    <PackageReference Include="ValueTaskSupplement" />
    <PackageReference Include="Vogen" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Physics\" />
    <Folder Include="Tools\Io\" />
  </ItemGroup>
</Project>