<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arch-Events" />
    <PackageReference Include="Arch.Relationships" />
    <PackageReference Include="ByteSize" />
    <PackageReference Include="dotVariant" />
    <PackageReference Include="Intellenum" />
    <PackageReference Include="MessagePipe" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.AutoActivation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Toolkit.HighPerformance" />
    <PackageReference Include="Nito.Disposables" />
    <PackageReference Include="QuikGraph" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Silk.NET.Core" />
    <PackageReference Include="System.Reactive.Interfaces" />
    <PackageReference Include="TruePath" />
    <PackageReference Include="ValueTaskSupplement" />
    <PackageReference Include="Vogen" />
    <PackageReference Include="ZLinq" />
  </ItemGroup>
</Project>